---
nginx:
  user: www-data
fix_modules_command:
  nginx: |
    curl https://nginx.org/keys/nginx_signing.key | gpg --yes --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
        | tee /etc/apt/sources.list.d/nginx.list
    apt update