---
- name: Deploy Frontend | Load Amazon or Ubuntu distribution variables
  ansible.builtin.include_vars: "vars/os_dependent/{{ ansible_facts['distribution']|lower }}{{ ansible_facts['distribution_major_version'] }}.yml"
  when: ansible_facts['distribution'] in ['Ubuntu','Amazon']

- name: Deploy Frontend | Load RedHat, CentOS, Oracle distribution variables
  ansible.builtin.include_vars: "vars/os_dependent/el{{ ansible_facts['distribution_major_version'] }}.yml"
  when: ansible_facts['distribution'] in ['CentOS','OracleLinux','RedHat']