- name: Unmount everything on the specific mountpoint
  become: true
  shell: "umount {{ appDir.appData_directory }}"
  register: umount_dir
  failed_when:
    - umount_dir.failed == true
    - '"not mounted" not in umount_dir.stderr'
    - '"no mount point specified" not in umount_dir.stderr'

- name: Create FS on the disk
  become: true
  shell: "mkfs.xfs /dev/{{ appdata_diskname }} -f"

- name: Create appdata mountpoint
  become: true
  file:
    path: "{{ appDir.appData_directory }}"
    state: directory
    mode: '0755'

- name: Create fstab entry for the dedicated disk
  become: true
  ansible.posix.mount:
    path: "{{ appDir.appData_directory }}"
    src: "/dev/{{ appdata_diskname }}"
    fstype: xfs
    opts: defaults
    state: present

- name: Mount the drive
  become: true
  shell: mount -a