apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.database.name }}-svc"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.database.servicePort }}
      targetPort: 3306
  selector:
    app: "{{ .Values.database.name }}-app"