apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.backend.name }}-svc"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: 30002
  selector:
    app: "{{ .Values.backend.name }}-app"