apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.backend.name }}-job-sa"
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.backend.name }}-job-role"
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.allPods.imagePullSecret }}"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.backend.name }}-job-rolebinding"
  namespace: default
subjects:
- kind: ServiceAccount
  name: "{{ .Values.backend.name }}-job-sa"
  namespace: default
roleRef:
  kind: Role
  name: "{{ .Values.backend.name }}-job-role"
  apiGroup: rbac.authorization.k8s.io




