apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.backend.name }}-app-sa"
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.backend.name }}-app-role"
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.allPods.imagePullSecret }}"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.backend.name }}-app-rolebind"
  namespace: default
subjects:
- kind: ServiceAccount
  name: "{{ .Values.backend.name }}-app-sa"
  namespace: default
roleRef:
  kind: Role
  name: "{{ .Values.backend.name }}-app-role"
  apiGroup: rbac.authorization.k8s.io




