apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}-svc"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: 80
  selector:
    app: "{{ .Values.frontend.name }}-app"