---
terraform:
  prerequisites:
    - ca-certificates
    - curl
    - gnupg
    - gnupg2
    - lsb-release
    - ubuntu-keyring
  repo_command: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    apt update -y
  package: terraform
nfs:
  package_name: nfs-kernel-server
  service_name: nfs-kernel-server