---
- name: Install Python and pip
  become: true
  package:
    name:
      - python3
      - python3-pip
    state: latest

- name: Install python module - PyMySQL
  become: true
  pip:
    name: pymysql
    state: present

- name: Install MariaDB
  become: true
  package:
    name: "{{ mariaDB.package }}"
    state: latest

- name: Stop MariaDB
  become: true
  service:
    name: mariadb
    state: stopped

- name: Remove any bind_address options from conf files
  become: true
  lineinfile:
    path: "{{ mariaDB.conf_file }}"
    state: absent
    regexp: 'bind-address'

- name: Make binding active an all interfaces
  become: true
  lineinfile:
    path: "{{ mariaDB.conf_file }}"
    regexp: '^bind-address'
    insertafter: '^[mariadb]'
    line: 'bind-address=0.0.0.0'

- name: Start MariaDB
  become: true
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create the new database
  become: true
  mysql_db:
    login_unix_socket: "{{ mariaDB.socket }}"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: ec2c
    state: present

- name: Copy database dump file
  become: true
  copy:
    src: ../configs/database/ec2c-dump.sql
    dest: /tmp

- name: Import database template
  become: true
  mysql_db:
    login_unix_socket: "{{ mariaDB.socket }}"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: ec2c
    state: import
    target: /tmp/ec2c-dump.sql

- name: Delete database dump file
  become: true
  ansible.builtin.file:
    path: /tmp/ec2c-dump.sql
    state: absent

- name: Create DB user for the app
  become: true
  mysql_user:
    login_unix_socket: "{{ mariaDB.socket }}"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: ec2cdbuser
    host: '%'
    password: "{{ dbuser_password }}"
    priv: "ec2c.*:ALL,GRANT"

