---
node:
  prerequisites:
    - ca-certificates 
    - curl 
    - gnupg 
    - gnupg2 
    - lsb-release 
    - ubuntu-keyring
  repo_command: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=20
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    apt update
  package: nodejs
nginx:
  user: www-data